// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: entry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType defines the different types of entries that can appear in the WAL.
// Each type serves a specific purpose in the WAL's operation and recovery process.
type EntryType int32

const (
	// Default zero value as required by proto3.
	// This should never appear in actual entries.
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	// Normal data entry containing user payload.
	// These form the majority of entries and contain actual data modifications.
	EntryType_ENTRY_TYPE_NORMAL EntryType = 1
	// Checkpoint entries mark consistent states in the WAL.
	// Used during recovery to find safe starting points and avoid replaying the entire log.
	// Contains metadata about the checkpoint state.
	EntryType_ENTRY_TYPE_CHECKPOINT EntryType = 2
	// Rotation entries indicate the start of a new segment.
	// Written when the WAL rotates to a new file.
	// Contains metadata about the old and new segments.
	EntryType_ENTRY_TYPE_ROTATION EntryType = 3
	// Marks entries that use compression.
	// The compression algorithm and level are specified in the header.
	// Used to optimize storage space.
	EntryType_ENTRY_TYPE_COMPRESSED EntryType = 4
	// System-level metadata entries.
	// Used for WAL management, configuration changes, and administrative data.
	// Not part of the user data stream.
	EntryType_ENTRY_TYPE_METADATA EntryType = 5
	// Segment header entries mark the beginning of a new WAL segment.
	// Contains initialization data like version, creation timestamp, and segment sequence number.
	// Required for segment validation and recovery.
	EntryType_ENTRY_TYPE_SEGMENT_HEADER EntryType = 6
	// Segment finalize entries mark a segment as complete and ready for archival.
	// Contains summary information like entry counts and checksums.
	// Used to verify segment integrity during recovery.
	EntryType_ENTRY_TYPE_SEGMENT_FINALIZE EntryType = 7
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_NORMAL",
		2: "ENTRY_TYPE_CHECKPOINT",
		3: "ENTRY_TYPE_ROTATION",
		4: "ENTRY_TYPE_COMPRESSED",
		5: "ENTRY_TYPE_METADATA",
		6: "ENTRY_TYPE_SEGMENT_HEADER",
		7: "ENTRY_TYPE_SEGMENT_FINALIZE",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED":      0,
		"ENTRY_TYPE_NORMAL":           1,
		"ENTRY_TYPE_CHECKPOINT":       2,
		"ENTRY_TYPE_ROTATION":         3,
		"ENTRY_TYPE_COMPRESSED":       4,
		"ENTRY_TYPE_METADATA":         5,
		"ENTRY_TYPE_SEGMENT_HEADER":   6,
		"ENTRY_TYPE_SEGMENT_FINALIZE": 7,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_entry_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_entry_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_entry_proto_rawDescGZIP(), []int{0}
}

// EntryHeader contains metadata and validation information for each WAL entry.
// Fixed-size structure that precedes every entry's payload.
type EntryHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of the entry, determining how it should be processed.
	// See EntryType enum for possible values.
	Type EntryType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EntryType" json:"type,omitempty"`
	// Unix timestamp in nanoseconds when the entry was created.
	// Used for time-based recovery and debugging.
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Size of the entry's payload in bytes.
	// Used to read variable-length payloads and verify integrity.
	PayloadSize uint32 `protobuf:"varint,3,opt,name=payloadSize,proto3" json:"payloadSize,omitempty"`
	// Used to detect corruption and ensure data integrity.
	Checksum uint64 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Offset of the previous entry in the log.
	// Enables backward traversal and helps in recovery.
	PrevOffset uint64 `protobuf:"varint,5,opt,name=prevOffset,proto3" json:"prevOffset,omitempty"`
	// Monotonically increasing sequence number.
	// Ensures proper ordering during recovery and helps detect missing entries.
	Sequence uint64 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Entry format version number.
	// Allows for future format changes while maintaining backward compatibility.
	// Using uint32 instead of uint8 for proto3 compatibility.
	Version       uint32 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryHeader) Reset() {
	*x = EntryHeader{}
	mi := &file_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryHeader) ProtoMessage() {}

func (x *EntryHeader) ProtoReflect() protoreflect.Message {
	mi := &file_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryHeader.ProtoReflect.Descriptor instead.
func (*EntryHeader) Descriptor() ([]byte, []int) {
	return file_entry_proto_rawDescGZIP(), []int{0}
}

func (x *EntryHeader) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *EntryHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EntryHeader) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *EntryHeader) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *EntryHeader) GetPrevOffset() uint64 {
	if x != nil {
		return x.PrevOffset
	}
	return 0
}

func (x *EntryHeader) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EntryHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Entry represents a complete WAL entry including its header and payload.
// This is the fundamental unit of storage in the WAL.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata and validation information for the entry.
	// Fixed-size structure with fields defined above.
	Header *EntryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Actual data payload of the entry.
	// Variable-length byte array containing the data to be written.
	// May be compressed according to the header's compression field.
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_entry_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetHeader() *EntryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Entry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_entry_proto protoreflect.FileDescriptor

var file_entry_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x76,
	0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x05,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0xe6, 0x01, 0x0a, 0x09,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x4e, 0x54,
	0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15,
	0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b,
	0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x54, 0x52, 0x59,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03,
	0x12, 0x19, 0x0a, 0x15, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43,
	0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x45, 0x44, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x45,
	0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x44, 0x41,
	0x54, 0x41, 0x10, 0x05, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x45,
	0x52, 0x10, 0x06, 0x12, 0x1f, 0x0a, 0x1b, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x41, 0x4c, 0x49,
	0x5a, 0x45, 0x10, 0x07, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x6d, 0x4e, 0x69, 0x6c, 0x6f, 0x74, 0x70, 0x61, 0x6c, 0x2f, 0x77,
	0x61, 0x6c, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entry_proto_rawDescOnce sync.Once
	file_entry_proto_rawDescData = file_entry_proto_rawDesc
)

func file_entry_proto_rawDescGZIP() []byte {
	file_entry_proto_rawDescOnce.Do(func() {
		file_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_entry_proto_rawDescData)
	})
	return file_entry_proto_rawDescData
}

var file_entry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entry_proto_goTypes = []any{
	(EntryType)(0),      // 0: proto.EntryType
	(*EntryHeader)(nil), // 1: proto.EntryHeader
	(*Entry)(nil),       // 2: proto.Entry
}
var file_entry_proto_depIdxs = []int32{
	0, // 0: proto.EntryHeader.type:type_name -> proto.EntryType
	1, // 1: proto.Entry.header:type_name -> proto.EntryHeader
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_entry_proto_init() }
func file_entry_proto_init() {
	if File_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entry_proto_goTypes,
		DependencyIndexes: file_entry_proto_depIdxs,
		EnumInfos:         file_entry_proto_enumTypes,
		MessageInfos:      file_entry_proto_msgTypes,
	}.Build()
	File_entry_proto = out.File
	file_entry_proto_rawDesc = nil
	file_entry_proto_goTypes = nil
	file_entry_proto_depIdxs = nil
}
